name: tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Java Test
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: spotlessCheck
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean test
